version: '3'

networks:
  linkedIn:
    external: true

services:
  node-nginx-post-service:
    build:
      context: .
      dockerfile: Dockerfile.node.nginx
    container_name: node-nginx-post-service
    # ports:
    #   - "12301:80"
    volumes:
      - ./src:/usr/share/nginx/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-post-service
    networks:
      linkedIn:
        ipv4_address: 172.20.0.13

  php-post-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-post-service
    user: "dipshikha:dipshikha"
    volumes:
      - ./src:/usr/share/nginx/html
    # ports:
    #   - "9000:9000"
    working_dir: /usr/share/nginx/html
    networks:
      linkedIn:
        ipv4_address: 172.20.0.14
    environment:
      - USER_SERVICE_URL="http://dslinked.in/user-service/"
      - POST_SERVICE_URL="http://dslinked.in/"
      - NOTIF_SERVICE_URL="http://dslinked.in/notif-service/"
      