version: '3'

networks:
  linkedIn:
    driver: bridge
    name: linkedIn
    ipam: 
      driver: default
      config:
        - subnet: 172.20.0.0/16

services:
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      linkedIn:
        ipv4_address: 172.20.0.2
  
  
  node-nginx-user-service:
    build:
      context: ./user-service/
      dockerfile: Dockerfile.node.nginx
    container_name: node-nginx-user-service
    volumes:
      - ./user-service/src:/usr/share/nginx/html
      - ./user-service/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-user-service
    networks:
      linkedIn:
        ipv4_address: 172.20.0.3

  php-user-service:
    build:
      context: ./user-service/
      dockerfile: Dockerfile
    container_name: php-user-service
    user: "dipshikha:dipshikha"
    volumes:
      - ./user-service/src:/usr/share/nginx/html
    working_dir: /usr/share/nginx/html
    networks:
      linkedIn:
        ipv4_address: 172.20.0.4
    environment:
      - USER_SERVICE_URL="http://dslinked.in/user-service/"
      - POST_SERVICE_URL="http://dslinked.in/"
      - NOTIF_SERVICE_URL="http://dslinked.in/notif-service/"

    
  node-nginx-post-service:
    build:
      context: ./post-service/
      dockerfile: Dockerfile.node.nginx
    container_name: node-nginx-post-service
    volumes:
      - ./post-service/src:/usr/share/nginx/html
      - ./post-service/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-post-service
    networks:
      linkedIn:
        ipv4_address: 172.20.0.13

  php-post-service:
    build:
      context: ./post-service/
      dockerfile: Dockerfile
    container_name: php-post-service
    user: "dipshikha:dipshikha"
    volumes:
      - ./post-service/src:/usr/share/nginx/html
    working_dir: /usr/share/nginx/html
    networks:
      linkedIn:
        ipv4_address: 172.20.0.14
    environment:
      - USER_SERVICE_URL="http://dslinked.in/user-service/"
      - POST_SERVICE_URL="http://dslinked.in/"
      - NOTIF_SERVICE_URL="http://dslinked.in/notif-service/"
  
  
  userdb-mongo-express:
    image: mongo-express
    container_name: userdb-mongo-express
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_URL=mongodb://root:password@userdb:27017/?authSource=admin
      - ME_CONFIG_BASICAUTH_USERNAME=mexpress
      - ME_CONFIG_BASICAUTH_PASSWORD=mexpress
    depends_on:
      - userdb
    restart: unless-stopped
    networks:
      linkedIn:
        ipv4_address: 172.20.0.5
  userdb:
    image: mongo:5.0
    container_name: userdb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    restart: unless-stopped
    # ports:
    #   - "27020:27017"
    volumes:
      - ./user-service/userdb/database/mongodb/db:/data/db
      - ./user-service/userdb/database/mongodb/dev.archive:/Databases/dev.archive
      - ./user-service/userdb/database/mongodb/production:/Databases/production
    command: [ "--auth" ]
    networks:
      linkedIn:
        ipv4_address: 172.20.0.6

  postdb-mongo-express:
    image: mongo-express
    container_name: postdb-mongo-express
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_URL=mongodb://root:password@postdb:27017/?authSource=admin
      - ME_CONFIG_BASICAUTH_USERNAME=mexpress
      - ME_CONFIG_BASICAUTH_PASSWORD=mexpress
    depends_on:
      - postdb
    restart: unless-stopped  
    networks:
      linkedIn:
        ipv4_address: 172.20.0.10
  postdb:
    image: mongo:5.0
    container_name: postdb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    restart: unless-stopped
    volumes:
      - ./post-service/postdb/database/mongodb/db:/data/db
      - ./post-service/postdb/database/mongodb/dev.archive:/Databases/dev.archive
      - ./post-service/postdb/database/mongodb/production:/Databases/production
    command: [ "--auth" ]
    networks:
      linkedIn:
        ipv4_address: 172.20.0.11