version: '3'

networks:
  linkedIn:
    driver: bridge
    name: linkedIn
    ipam:
      driver: default
      config: 
        -subnet: 172.20.0.0/16

services:
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      linkedIn:
        ipv4_address: 172.20.0.2